mendersoftware/useradm

.travis.yml

Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
@mchalski found this during merge build - skipped deploy step (deploy & before_deploy) so didn't get container in docker hub

MEN-794: Perform deployment for all repos.

---

authz_simple.go
useradm.go

this causes 403 errors on pretty much any management API call in the system.
note that all these requests are routed to /verify first - which subsequently
denies access since the authorizer tries to check the request against useradm's
own authz rules.
the quick solution is to make the authorizer aware of this, and return asap on POST /verify.
effectively, the actual authz will be delegated to the target downstream service;
useradm will only check the token validity, as it should.
also - skip checking the db on Verify() if it's the initial user creation request; we know there's no user, so the check will fail.
Issues: MEN-907

authz_simple: skip auth rules checking on POST /verify

---

api_useradm_test.go
authz/middleware.go
authz/middleware_test.go
authz_simple.go
authz_simple_test.go
middleware.go

Issues: https://tracker.mender.io/browse/MEN-918
use the X-Original-URI and X-Original-Method headers to extract the *target* service name+http method and use these in authz checks. this clears up the bug in question, as well as makes the authz code more explicit and easier to reason about.
as a side note - a couple of thoughts on our authz middleware and authz infrastructure in general can be found in the jira comment section (basically, needs some decisions/refactoring, but post 1.0).

explicitly use destination service name and action in authz rules

---

.travis.yml

supposedly, this magic will make useradm's swagger appear in the docs site.
goes with https://github.com/mendersoftware/mender-docs/pull/100
Issues: MEN-976

travis: deploy useradm docs to site docs

---

commands.go
commands_test.go
main.go
user/useradm.go

Issues: MEN-1256
make the `create-user` cli multitenant-aware by accepting a `--tenant-id`.
also, allow the user to set `--user-id`

create-user cli fixes (MT)

---

user/useradm.go
user/useradm_test.go

the tenant's identity was never added into the context, so
the data layer could not select the db correctly (DbFromContext).
this caused failures at login in mutitenant scenarios.
Issues: MEN-1312

user: correctly prepare context with tenant id at Login

---

user/useradm.go

don't return after successful tenantadm communication - otherwise
we never get to the DB creation code.
Issues: MEN-1312

user: actually create the user in mt-setup

---

.travis.yml
client/tenant/client_tenantadm.go
tests/docker-compose-acceptance-multitenant.yml
tests/docker-compose-acceptance.yml
tests/tests/tenantadm.py
tests/tests/test_api_management.py

this fixes several issues I bumped upon during MEN-1284.
multitenancy was never properly enabled because of a mistake in the tenantadm address env; the tests were effectively single-tenant.
otoh the fake tenantadm was never started even for MT-tests, so to put it shortly, everything was wrong on many levels.
this PR:
- sets up correct single-tenant and multi-tenant compose files
- runs them both in travis
- implements a fake tenantadm create-user handler, and runs it in MT tests
- fixes a json encoding bug in `useradm` itself (invalid field names in `tenantadm` requests)

fix multitenant acceptance tests

---

api/http/api_useradm.go
api/http/api_useradm_test.go
api/http/middleware.go
docs/internal_api.yml
tests/tests/client.py

@mendersoftware/rndity 
needs to go with https://github.com/mendersoftware/mender-api-gateway-docker/pull/78
The change is needed so that we can selectively expose only management endpoints on the gateway. Otherwise, if we add a tenant endpoint now, it will still be possible to access it through the gateway with a specially crafted URL.

align URLs

---

.travis.yml

https://tracker.mender.io/browse/QA-27
if that's ok, I'll repeat this for all services.
changelog: none
PS. tried to also emit coverage report a'la acceptance tests by making some stuff common between the two (dockerfile driven by env vars, etc.) but this needs more consideration because of a lot of stupid quirks. do we want that? then I'll think about doing it independently from what we have in acceptance tests now.

travis: run backend integration tests    

---

.gitlab-ci.yml
.travis.yml
tests/docker-compose-acceptance-enterprise.yml
tests/docker-compose-acceptance.yml
tests/tests/test_api_internal.py
tests/tests/test_api_management.py
tests/tests/test_auth.py
tests/tests/test_cli.py
tests/tests/test_tokens_delete.py

The last two commits are not entirely in scope of the issue, but are rather to align the remainder of the code with the enterprise naming (I'll just drop the commits and update if this should be put into a separate issue instead)

Men 2655 align enterprise naming in tests

---

.gitlab-ci.yml

Acceptance tests are failing since last week. This is a temporary workaround. See:
* https://gitlab.com/gitlab-com/support-forum/issues/5194#note_288438588
* MEN-3200
ChangeLog:none

MEN-3200 docker image change: a workaround for failing acceptance tests

---

commands.go

The migrate command, when used without the `--tenant` option, migrates
the database of all the tenants. This behaviour is consistent with the
`--automigrate` option of the `server` command.
If the `--tenant` option is specified, the migration runs only for the
provided tenant ID.

Update migrate command to be consistent with server --automigrate

---

docs/internal_api.yml
docs/management_api.yml

* [API spec] Consistently use host hosted.mender.io across all repos
* [API spec] Consistently use https schemes across all repos

API spec fixes: schema and hostname

---

api/http/api_useradm.go
api/http/api_useradm_test.go
docs/internal_api.yml
docs/management_api.yml
model/user.go
model/user_test.go
store/datastore.go
store/mocks/DataStore.go
store/mongo/datastore_mongo.go
store/mongo/datastore_mongo_test.go
user/mocks/App.go
user/useradm.go
user/useradm_test.go

Updated endpoint `POST /api/(management|internal)/v1/useradm/tenants/:id/users` with an `id` parameter to filter by user `id`s (needed by MEN-3749/3750).

api: New internal endpoint for getting user info

---

user/useradm.go

The NotBefore claim is not set, making it constant at the zero datetime
value.

Set "nbf" to current date

---

store/mongo/datastore_mongo.go

This is a noop for the open-source repository, but required for the enterprise version (related to MEN-4041).

store: Update user returns old document instead of new

---

store/mongo/migration_1_1_4.go
store/mongo/migration_1_1_4_test.go

The migration fails if index with name `uniqueName` exists.

store/mongo: Fix migration_1_4_0

---

user/useradm.go

The NewUUIDv5 function for given email returns same id.
If user changed email, and the old one is used in
the new user creation, the error says:
tenant data out of sync: user with the same name already exists
ChangeLog:none

New user generation fix

---

tests/tests/client.py

To align it with the rest of the repositories.

tests: add prefix /usr/bin to the CliClient command

---

api/http/api_useradm.go
api/http/api_useradm_test.go
client/tenant/client_tenantadm.go
client/tenant/client_tenantadm_test.go
tests/run.sh

Ticket: MEN-5713
(cherry picked from commit 097936aa0e00671f3aed11937e67b74c970a2c0f)

fix: replace colon with hash for path params modifiers in URLs

---

model/user.go

Etags are not exposed to the v1 API and should be set using headers (RFC7232).

chore(cleanup): Do not expose "ETagUpdate" to update endpoint

---

model/user.go
store/mongo/datastore_mongo.go
store/mongo/datastore_mongo_test.go
user/useradm.go

This commit restores the old behavior by default.

fix: Make user updates default to skip ETag checks (wildcard match)

---

server.go
user/useradm.go
user/useradm_test.go

We renamed it in the enterprise fork; rename it in the open-source flavour to make it consistent.
Ticket: None

chore: rename ExpirationTime to ExpirationTimeSeconds

---

Dockerfile
Dockerfile.acceptance-testing

Removes build host specific paths from traces.

chore(docker): Add -trimpath to go build command
