mendersoftware/useradm

- Dockerfile
> dockerfile fix: copy the privkey

- middleware.go
- middleware_test.go
- server.go
- server_test.go
a `nil` handler was causing panic on `verify`
Issues: MEN-904
> bugfix: set JWTHandler for the authz middleware

- Dockerfile
Fixes: [Mender #908]
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> Dockerfile: do not ship token signing key in the image

- docs/management_api.yml
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
> rename integrations_api.yml -> management_api.yml

- api_useradm.go
Issues: MEN-881
see: https://tools.ietf.org/html/rfc3986#section-5.4
@mendersoftware/rndity  @maciejmrowiec
> api_useradm: relative url in Location header

- datastore.go
- datastore_mock_test.go
- datastore_mongo.go
- datastore_mongo_test.go
- main.go
- vendor/github.com/mendersoftware/go-lib-micro/LIC_FILES_CHKSUM.sha256
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/db.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migration.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migrator.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migrator_dummy.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/version.go
- vendor/vendor.json
> Mongo schema version

- .travis.yml
Changelog: none
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
> travis: Install python-xdist to leverage parallel tests

- main.go
- store/mongo/datastore_mongo.go
> mongo fsync & ack

- config.go
> config: introduce TenantAdmAddr setting

- docs/management_api.yml
Description can be found here: https://tracker.mender.io/browse/MEN-828
> docs: API for local user management

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- model/model_user.go
- store/mongo/datastore_mongo.go
- utils/testing/context.go
https://tracker.mender.io/browse/MEN-831
> post /users endpoint implementation

- commands.go
- commands_test.go
- config.go
- config.yaml
- db.go
- db_test.go
- main.go
- server.go
- store/mongo/datastore_mongo.go
Expose new db connection settings to application configuration: ssl, ssl skip verify, user, pass.
Minor logging improvement on opening connection to db.
> SSL support for MongoDB connections.

- .travis.yml
- Dockerfile.acceptance-testing
- main.go
- main_test.go
- tests/Dockerfile
- tests/conftest.py
- tests/docker-compose-acceptance.yml
- tests/run.sh
- tests/tests/test_dummy.py
- vendor/github.com/mendersoftware/go-lib-micro/log/testing/log.go
- vendor/vendor.json
basic acceptance tests setup with a dummy passing test.
reminder: after merge check if a new image was pushed to dockerhub.
Issues: MEN-834
@mendersoftware/rndity @GregorioDiStefano
> acceptance tests setup

- .travis.yml
@GregorioDiStefano @kjaskiewiczz @maciejmrowiec
> travis: try fixing before_deploy syntax error

- client/tenant/client_tenantadm.go
- client/tenant/client_tenantadm_test.go
- client/tenant/mocks/ClientRunner.go
- user/useradm.go
- user/useradm_test.go
> propagate user edits to tenantadm

- client/tenant/client_tenantadm.go
- client/tenant/client_tenantadm_test.go
- client/tenant/mocks/ClientRunner.go
- user/useradm.go
- user/useradm_test.go
Propagate delete user operation to tenantadm.
Issues: https://tracker.mender.io/browse/MEN-1277
> useradm: delete user in tenantadm

- .travis.yml
- Dockerfile.acceptance-testing
> acceptance fix config path

- .travis.yml
- tests/Dockerfile
- tests/common.py
- tests/docker-compose-acceptance.yml
- tests/tests/client.py
- tests/tests/mockserver.py
- tests/tests/tenantadm.py
- tests/tests/test_api_management.py
https://tracker.mender.io/browse/MEN-1282
the integration tests don't pass, but the PR is ready for review; we'll try to resolve the build issues separately, I don't think they're related to the changeset itself.
> setup clients, mockserver, test POST /verify

- tests/tests/client.py
- tests/tests/test_api_management.py
> acceptance tests: GET /users/<id>

- tests/docker-compose-acceptance-multitenant.yml
- tests/docker-compose-acceptance.yml
- tests/tests/test_api_management.py
https://tracker.mender.io/browse/MEN-1283
> acceptance tests: GET /users 

- tests/tests/client.py
- tests/tests/tenantadm.py
- tests/tests/test_api_management.py
https://tracker.mender.io/browse/MEN-1286
> acceptance tests: delete device endpoint tests

- client/tenant/client_tenantadm.go
- tests/common.py
- tests/tests/client.py
- tests/tests/tenantadm.py
- tests/tests/test_api_management.py
- user/useradm.go
Issue: https://tracker.mender.io/browse/MEN-1285
also contains some bugfixes for the service - one critical (user was never updated in the db if MT was enabled).
> acceptance: PUT /users/<id>

- client/tenant/client_tenantadm.go
caused 415 in testing.
tested manually, fixes the scenario from jira description.
Issues: MEN-1336
@maciejmrowiec @mendersoftware/rndity @GregorioDiStefano
> client/tenant: set content-type manually in post/put reqs

- commands.go
works like tenantadm's create-tenant
Issues: MEN-1333
@maciejmrowiec @mendersoftware/rndity @GregorioDiStefano
> commands: make create-user print out the user ID

- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
https://tracker.mender.io/browse/MEN-1386
> ensure db indexes on all write operations

- user/useradm.go
Changes:
- tokens without tenant claim will be rejected by multi tenant setup;
- tokens with tenant claim will be rejected by single tenant setup.
https://tracker.mender.io/browse/MEN-1327
> user/verify token: handle tenant claim (or lack of it) properly

- model/model_user.go
Issues: MEN-1258
Changelog: none
@kjaskiewiczz
> model: omit empty password from returned json structs

- docs/internal_api.yml
- tests/common.py
- tests/tests/client.py
- tests/tests/tenantadm.py
- tests/tests/test_auth.py
- tests/tests/test_cli.py
- tests/tests/test_dummy.py
> auth acceptance tests 

- jwt/claims.go
- tests/tests/test_auth.py
- user/useradm.go
- user/useradm_test.go
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> MEN-1418 `mender.user` claim

- commands.go
everything was in place for this to happen, except
correct configuration of useradm.WithTenantVerification
based on the relevant env var.
Issues: MEN-1311
> commands: propagate new user to tenantadm 

- .travis.yml
- commands.go
- main.go
- store/mongo/datastore_mongo.go
- tests/tests/client.py
- tests/tests/test_cli.py
> 'migrate [--tenant=<id>]' command 

- tests/tests/client.py
- tests/tests/test_api_internal.py
Issues: MEN-1575
Signed-off-by: Piotr Przybylak <piotr.przybylak@rndity.com>
> Acceptance testst for Create User API

- .travis.yml
> travis: remove deprecated --email flag on 'docker login'

- commands.go
- main.go
- store/mongo/datastore_mongo.go
- user/mocks/App.go
- user/useradm.go
- user/useradm_test.go
Issues: MEN-1673
Signed-off-by: Piotr Przybylak <piotr.przybylak@gmail.com>
> useradm --set-password

- main.go
> useradm --set-password - Fix command  

- tests/tests/client.py
- tests/tests/test_cli.py
Issue: https://tracker.mender.io/browse/MEN-1684
@mendersoftware/rndity @GregorioDiStefano @maciejmrowiec
> acceptance tests: useradm --set-password cli command

- docs/internal_api.yml
Issue: https://tracker.mender.io/browse/MEN-1698
Epic: https://tracker.mender.io/browse/MEN-1685
@mchalski @maciejmrowiec @GregorioDiStefano
> docs/API: internal endpoint for removing user tokens

- commands.go
- jwt/claims.go
- jwt/jwt.go
- jwt/jwt_test.go
- jwt/token.go
- main.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- user/mocks/App.go
- user/useradm.go
- user/useradm_test.go
- vendor/github.com/mendersoftware/mendertesting/check_license_go_code.sh
- vendor/vendor.json
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Update mendertesting dependency and affected copyright years.

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- client/tenant/client_tenantadm.go
- user/useradm.go
- user/useradm_test.go
Issues: https://tracker.mender.io/browse/MEN-1707
> token issuing process extended with suspended tenant account handling

- docs/management_api.yml
Issues: https://tracker.mender.io/browse/MEN-1885
> docs: spec of the management endpoint with global user settings

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
https://tracker.mender.io/browse/MEN-1888
> GET /settings  

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- tests/tests/client.py
- tests/tests/test_api_management.py
depends on https://github.com/mendersoftware/useradm/pull/116 for now
https://tracker.mender.io/browse/MEN-1887
> test POST /settings

- tests/tests/tenantadm.py
- tests/tests/test_auth.py
https://tracker.mender.io/browse/MEN-1708
> test auth fails for suspended tenant

- .travis.yml
- api/http/api_useradm_test.go
- docs/management_api.yml
- model/user.go
- model/user_test.go
https://tracker.mender.io/browse/MEN-2025
> reject '+' and non-ascii chars in email on user creation

- LICENSE
- LIC_FILES_CHKSUM.sha256
- user/useradm.go
- vendor/github.com/mendersoftware/mendertesting/LICENSE
. return unauthorised response for logins with empty username
. Copyright date incremented
. Licenses files changed
. checksums on licenses updated
Signed-off-by: Peter Grzybowski <piotr@northern.tech>
> MEN-2375 unauthorised for empty username logins

- Dockerfile
> Dockerfile: added multi stage docker build steps to allow build independent of go env

- .gitlab-ci.yml
- Dockerfile.acceptance-testing
- tests/Dockerfile
- tests/run.sh
> added gitlab-ci pipeline

- .travis.yml
Important for the license check test.
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Make sure all branches are fetched also in unit test stage.

- store/mongo/datastore_mongo.go
- tests/common.py
Issues: https://tracker.mender.io/browse/MEN-2971
> store/mongo: handle mongodb client creation error

- .gitlab-ci.yml
- Dockerfile.acceptance-testing
- tests/docker-compose-integration.yml
Use of CI templates and clean-ups.
Depends on https://github.com/mendersoftware/mendertesting/pull/43, commit [77830cd](https://github.com/mendersoftware/useradm/pull/151/commits/77830cdb0e295e4cd2b9a433c3378ce44aac4770) will be removed before merge
> QA-149: Use pipelines templates 

- .gitlab-ci.yml
- Dockerfile.acceptance-testing
- tests/docker-compose-integration.yml
> QA-149: Use pipelines templates - 1.10.x

- .github/stale.yml
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
> add(stalebot): Add a configuration file for stalebot

- vendor/github.com/mendersoftware/go-lib-micro/accesslog/middleware.go
- vendor/github.com/mendersoftware/go-lib-micro/identity/middleware.go
- vendor/github.com/mendersoftware/go-lib-micro/identity/token.go
- vendor/vendor.json
> Upgrade vendorized go-lib-micro to latest version

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- api/http/middleware.go
resurrection of #149
+ test to see if the GET access is possible
> Allow token verification on get

- store/mongo/datastore_mongo.go
> Remove mongodb write concern, let the connection string set them

- docs/internal_api.yml
- docs/management_api.yml
> API spec fixes: schema and hostname - 1.11.x

- api/http/api_useradm_test.go
- client/tenant/client_tenantadm.go
- docs/management_api.yml
- model/user.go
- model/user_test.go
> MEN-1969: add support for the + character in the email address

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- authz/middleware.go
- docs/management_api.yml
- server.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- tests/tests/client.py
- tests/tests/mockserver.py
- tests/tests/tenantadm.py
- tests/tests/test_api_internal.py
- tests/tests/test_api_management.py
- tests/tests/test_auth.py
- tests/tests/test_cli.py
- tests/tests/test_tokens_delete.py
- user/mocks/App.go
- user/useradm.go
- user/useradm_test.go
> MEN-3943: new API end-point logout

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- authz/middleware_test.go
- authz_simple_test.go
- client/tenant/client_tenantadm_test.go
- jwt/jwt_test.go
- model/user.go
- model/user_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- tests/tests/test_api_management.py
- user/useradm.go
- user/useradm_test.go
> MEN-3950: remove JWT all user tokens but the current one on password change

- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_1_4.go
- store/mongo/migration_1_1_4_test.go
- store/mongo/migrations.go
Issue: https://tracker.mender.io/browse/MEN-4040
> store: fix unique email index

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- docs/management_api.yml
> MEN-4046: support /me API paths to get and update the current user

- api/http/api_useradm_test.go
- api/http/middleware.go
- docs/internal_api.yml
- tests/tests/client.py
changelog: title
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> use traefik's X-Forwarded-* headers

- client/tenant/client_tenantadm.go
- model/user.go
Prevents a potential email leakage from the logs.
> MEN-4332: Redact sensitive information from logs

- tests/Dockerfile
- tests/common.py
- tests/docker-compose-acceptance-enterprise.yml
- tests/docker-compose-acceptance.yml
- tests/tests/client.py
- tests/tests/test_api_internal.py
- tests/tests/test_cli.py
- tests/tests/test_tokens_delete.py
https://tracker.mender.io/browse/QA-260
> use common acceptance tests image

- api/http/api_useradm.go
- docs/management_api.yml
- model/user.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- tests/tests/test_api_management.py
- user/useradm.go
- user/useradm_test.go
> MEN-4922: require the current one when updating the user's password

- api/http/api_useradm.go
- api/http/api_useradm_test.go
> added setting JWT cookie on successful login to align with oauth behaviour

- docs/internal_api.yml
Fix internal api spec
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> Fix internal api spec

- api/http/api_useradm.go
- api/http/api_useradm_test.go
> fix: aligned cookie settings with GUI

- Dockerfile
- Dockerfile.acceptance-testing
> chore: moved docker images away from root

- store/mongo/migration_1_3_2.go
- store/mongo/migration_1_3_2_test.go
- store/mongo/migrations.go
> fix(migrations): version fixed

- docs/management_api.yml
- store/mongo/migration_1_3_2.go
Changes:
- store: unique index in the tokens collection fixed;
- docs: token properties fixed
> Personal Access Token fixes

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- commands.go
- main.go
- model/user.go
- model/user_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- user/mocks/App.go
- user/useradm.go
- user/useradm_test.go
Ticket: MEN-3524
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
> fix(schema): Make username/email case-insensitive

- tests/common.py
- tests/run.sh
- tests/tests/client.py
- tests/tests/test_api_internal.py
- tests/tests/test_api_management.py
- tests/tests/test_api_personal_access_tokens.py
- tests/tests/test_auth.py
- tests/tests/test_cli.py
- tests/tests/test_tokens_delete.py
* Database migration test fixed
* DB migrations added before each test class
Ticket: MEN-5667
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> MEN-5667: Fix acceptance tests

- store/mongo/migrations.go
- tests/tests/test_api_internal.py
- tests/tests/test_cli.py
> fix: do not create tenant-specific databases when creating tenants

- store/mongo/migrations.go
> fix: run migrations on tenant-specific databases first, then global db

- tests/tests/test_api_management.py
- user/useradm.go
- user/useradm_test.go
Ticket: MEN-5731
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
> fix: invalidate user sessions but the current one on user updates

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- client/tenant/client_tenantadm.go
- client/tenant/client_tenantadm_test.go
> fix: replace colon with hash for path params modifiers in URLs

- tests/tests/test_api_management.py
- user/useradm.go
- user/useradm_test.go
Ticket: MEN-5738
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
> fix: require password prompt for changing email

- docs/internal_api.yml
chore(api-docs): Update internal API docs - propagate property removed
Ticket: MEN-5733
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> chore(api-docs): Update internal API docs - propagate property removed

- user/useradm.go
> feat: do not check the JWT issuer.

- server.go
> chore: A trace of history in logs (misc)

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- model/user.go
- model/user_test.go
- store/mongo/datastore_mongo.go
- user/useradm.go
- user/useradm_test.go
> Cherry-pick MEN-6003 to 1.19.x (3.4.x)

- api/http/api_useradm.go
- api/http/api_useradm_test.go
- docs/management_api.yml
- model/user.go
- model/user_test.go
- store/datastore.go
- store/mongo/datastore_mongo.go
- tests/common.py
- tests/tests/test_api_management.py
- user/useradm.go
- user/useradm_test.go
NOTE: The 3.3.x branch is diverging quite a lot so I had to pull in some dependencies into the cherry commits.
> Cherry-pick MEN-5829 and MEN-6003 to 1.18.x (mender 3.3.x)

- model/user.go
> chore(cleanup): Do not expose "ETagUpdate" to update endpoint

- model/user.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- user/useradm.go
- user/useradm_test.go
Ticket: MEN-6087
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
(cherry picked from commit 079780b82e59597954dca882bd11270f24b62c6f)
> Cherry-pick MEN-6087 to 1.18.x (mender-3.3.x)

- store/mongo/migration_2_0_3.go
- store/mongo/migrations.go
- store/mongo/migrations_test.go
- tests/tests/test_cli.py
The version is already taken in enterprise version.
> chore: Fix migration version conflict

- .gitlab-ci.yml
- Dockerfile
Ticket: QA-613
Changelog: Added multiplatform build
> Multiplatform build

- Dockerfile
- Dockerfile.acceptance-testing
- api/http/api_useradm.go
- api/http/api_useradm_test.go
- config/config.go
- config/plans.yaml
- docs/management_api.yml
- main.go
- model/plans.go
- user/mocks/App.go
- user/useradm.go
- user/useradm_test.go
Ticket: [ALV-116](https://northerntech.atlassian.net/browse/ALV-116)
[ALV-116]: https://northerntech.atlassian.net/browse/ALV-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: introduce plans API

- api/http/api_useradm.go
- api/http/api_useradm_test.go
to go with https://github.com/mendersoftware/gui/pull/4104
Ticket: SEC-944
> SEC-944 - fix: removed jwt cookie transmission to minimize potential leakage of auth info
